### PR TITLE
Sample Notebooks for the New Python Client

### PR DESCRIPTION
**Pull request by mtanco**

### CODE REVIEW

**Comment by g-eoj** [comment]
This is pretty cool! Some notes:
- head/tail in beta will return a table so you won't need Pandas
- instead of import `h2oai_client`, you could do `dai._backend` to get the MLI functions. just continue to be explicit that `_backend` is not stable and won't be supported.

**Comment by mtanco** [comment]
Thanks @g-eoj ! I will rerun these all on the official release when it comes out and update the head/tail make sure everything still works.

Good idea on the _backend!

**Comment by g-eoj** [comment]
@mtanco should we add a README to this folder to let users know the beta client is different from what ships with DAI?

**Comment by mtanco** [comment]
Yes! Do you want to use your current client read me? I think everyone should start added examples and tutorials here - and a read me is good for that too

**Comment by mtanco** [comment]
Readme done - in separate push

**Pull request merged**
